### ISSUE TITLE
Directory venv_srcpm not exist when docker build

### ISSUE THREAD

**Issue by Oritz** [creditease-sec/insight#1]
Step 12/14 : COPY srcpm/venv_srcpm/lib/python2.7/site-packages/flask_bootstrap/__init__.py /lib/python2.7/site-packages/flask_bootstrap/__init__.py
COPY failed: stat /var/lib/docker/tmp/docker-builder076187036/srcpm/venv_srcpm/lib/python2.7/site-packages/flask_bootstrap/__init__.py: no such file or directory

**Comment by liusec** [comment]
已增加docker build文件
