### ISSUE TITLE
新用户收到的注册激活邮件链接有误

### ISSUE THREAD

**Issue by ghost-snow** [creditease-sec/insight#43]
注册新用户-邮箱激活步骤：发现激活邮件中给出的激活链接地址是以“http://127.0.0.1/srcpm...+token”形式的链接，请教此处“http://127.0.0.1”这个地址如何修改为云主机的公网IP（srcpm已部署至云主机环境）?
我容器启动时运行的地址是docker run -d -p 0.0.0.0:9000:5000...
当使用以下命令启动容器(替换为我公网IP)：
docker run -d -p 47.xx.xx.100:9000:5000 \....\...\...\
则会报错：
docker: Error response from daemon: driver failed programming external connectivity on endpoint open_source_srcpm (07b77b355b72017f2f3742b356b6d0051f80d245bc8c1e91fdb78df328ca43ce): Error starting userland proxy: listen tcp 47.XX.XX.100:9000: bind: cannot assign requested address.
请教详细配置步骤，如何修改配置才能实现激活邮件中的激活链接地址自动更改为我云主机的公网IP
@liusec @wsjswy

**Comment by ddzzj** [comment]
你应该替换为该服务器的私有地址。公网地址是在网关上的，docker无法获取到。

**Comment by ghost-snow** [comment]
> 你应该替换为该服务器的私有地址。公网地址是在网关上的，docker无法获取到。

设置服务器的私有地址？我查到容器的ip是172.17.0.3。
我将此地址替换为：docker run -d -p 172.17.0.3:9000:5000 ..........后仍然报错：
docker: Error response from daemon: driver failed programming external connectivity on endpoint open_source_srcpm (cbf76c7bb7d27b0b905160388e18e445b014be80cc418489e8dd9b5f7f9c79d5): Error starting userland proxy: listen tcp 172.17.0.3:9000: bind: cannot assign requested address.

**Comment by ghost-snow** [comment]
问题进展：此问题怀疑与我在服务器层面加了nginx反向代理有关：
nginx.conf :
---
    server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  xxx.com;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
        proxy_pass http://127.0.0.1:9000;
        }
----
此处加nginx反向代理的意义在于可以直接通过我公网ip访问到容器的srcpm应用。。
目前还不清楚有什么办法可以解决激活邮件中链接问题。

**Comment by ghost-snow** [comment]
> ## 问题进展：此问题怀疑与我在服务器层面加了nginx反向代理有关：
> nginx.conf :
> ```
> server {
>     listen       80 default_server;
>     listen       [::]:80 default_server;
>     server_name  xxx.com;
>     root         /usr/share/nginx/html;
> 
>     # Load configuration files for the default server block.
>     include /etc/nginx/default.d/*.conf;
> 
>     location / {
>     proxy_pass http://127.0.0.1:9000;
>     }
> ```
> 此处加nginx反向代理的意义在于可以直接通过我公网ip访问到容器的srcpm应用。。
> 目前还不清楚有什么办法可以解决激活邮件中链接问题。

问题关闭，最终解决办法是关掉nginx，docker -d -p 9000:5000......
