### ISSUE TITLE
srcpm/src/assets_modify/1  error

### ISSUE THREAD

**Issue by yuxiaokui** [creditease-sec/insight#7]
Sorry,internal server error!
BuildError: Could not build url for endpoint 'src.assets_add_ajax'. Did you mean 'src.assets_add' instead?

2018/4/17 下午2:34:42[2018-04-17 06:34:42,274] ERROR in app: Exception on /srcpm/src/assets_modify/1 [GET]
2018/4/17 下午2:34:42Traceback (most recent call last):
2018/4/17 下午2:34:42  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
2018/4/17 下午2:34:42    response = self.full_dispatch_request()
2018/4/17 下午2:34:42  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
2018/4/17 下午2:34:42    rv = self.handle_user_exception(e)
2018/4/17 下午2:34:42  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
2018/4/17 下午2:34:42    reraise(exc_type, exc_value, tb)
2018/4/17 下午2:34:42  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
2018/4/17 下午2:34:42    rv = self.dispatch_request()
2018/4/17 下午2:34:42  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
2018/4/17 下午2:34:42    return self.view_functions[rule.endpoint](**req.view_args)
2018/4/17 下午2:34:42  File "/opt/webapp/srcpm/app/decorators.py", line 13, in decorated_function
2018/4/17 下午2:34:42    return f(*args, **kwargs)
2018/4/17 下午2:34:42  File "/opt/webapp/srcpm/app/src/views.py", line 1223, in assets_modify
2018/4/17 下午2:34:42    return render_template('src/assets_modify.html', form=form, id = asset_get.id)
2018/4/17 下午2:34:42  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
2018/4/17 下午2:34:42    context, ctx.app)
2018/4/17 下午2:34:42  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 116, in _render
2018/4/17 下午2:34:42    rv = template.render(context)
2018/4/17 下午2:34:42  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
2018/4/17 下午2:34:42    return self.environment.handle_exception(exc_info, True)
2018/4/17 下午2:34:42  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
2018/4/17 下午2:34:42    reraise(exc_type, exc_value, tb)
2018/4/17 下午2:34:42  File "/opt/webapp/srcpm/app/templates/src/assets_modify.html", line 2, in top-level template code
2018/4/17 下午2:34:42    {% import 'bootstrap/wtf.html' as wtf %}
2018/4/17 下午2:34:42  File "/opt/webapp/srcpm/app/templates/base.html", line 1, in top-level template code
2018/4/17 下午2:34:42    {% extends 'bootstrap/base.html' %}
2018/4/17 下午2:34:42  File "/usr/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
2018/4/17 下午2:34:42    {% block doc -%}
2018/4/17 下午2:34:42  File "/usr/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
2018/4/17 下午2:34:42    {%- block html %}
2018/4/17 下午2:34:42  File "/usr/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
2018/4/17 下午2:34:42    {% block body -%}
2018/4/17 下午2:34:42  File "/usr/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 26, in block "body"
2018/4/17 下午2:34:42    {% block scripts %}
2018/4/17 下午2:34:42  File "/opt/webapp/srcpm/app/templates/src/assets_modify.html", line 17, in block "scripts"
2018/4/17 下午2:34:42    url:"{{ url_for('src.assets_add_ajax') }}",
2018/4/17 下午2:34:42  File "/usr/lib/python2.7/site-packages/flask/helpers.py", line 332, in url_for
2018/4/17 下午2:34:42    return appctx.app.handle_url_build_error(error, endpoint, values)
2018/4/17 下午2:34:42  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1811, in handle_url_build_error
2018/4/17 下午2:34:42    reraise(exc_type, exc_value, tb)
2018/4/17 下午2:34:42  File "/usr/lib/python2.7/site-packages/flask/helpers.py", line 322, in url_for
2018/4/17 下午2:34:42    force_external=external)
2018/4/17 下午2:34:42  File "/usr/lib/python2.7/site-packages/werkzeug/routing.py", line 1776, in build
2018/4/17 下午2:34:42    raise BuildError(endpoint, values, method, self)
2018/4/17 下午2:34:42BuildError: Could not build url for endpoint 'src.assets_add_ajax'. Did you mean 'src.assets_add' instead?

**Comment by yuxiaokui** [comment]
搞定了。。   views  最下面的注释，干掉就可以了。

**Comment by liusec** [comment]
感谢提交，去掉注释的代码已经更新，当时估计是手抖了。😄
